---
services:
  redis:
    # networks:
    #   - redis-network
    command:
      - redis-server
      - "--appendonly"
      - "yes"
      - "--requirepass ${REDIS_PASSWORD}"
    image: redis
    container_name: blackbird-redis
    restart: always
    expose:
      - 6379
    ports:
      - "${REDIS_HOST_PORT:-6379}:${REDIS_PORT:-6379}"

  api:
    # networks:
    #   - api-network
    #   - redis-network
    env_file:
      - .env
    build: .
    command: /bin/sh -c "yarn && yarn migrate:deploy && yarn dev:api"
    container_name: blackbird-api
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - redis
      - pgsql
      - minio
    ports:
      - "${APP_HOST_PORT:-3000}:3000"
    restart: always
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/var/www/api
      - ${MEDIA_LOCATION:-./data/media/}downloadCache:/data/media/downloadCache

  background:
    # networks:
    #   - api-network
    #   - redis-network
    env_file:
      - .env
    build: background
    # command: /bin/sh -c "yarn && yarn migrate && yarn start:dev"
    container_name: blackbird-background
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - redis
      - pgsql
      - api
      - minio
    restart: always
    volumes:
      - ~/.ssh:/root/.ssh
      - ./:/var/www/api
      - ${MEDIA_LOCATION:-./data/media/}processing:/data/media/processing
      # - ${MEDIA_LOCATION:-./data/media/}audio:/data/media/audio
      # - ${MEDIA_LOCATION:-./data/media/}images:/data/media/images

  minio:
    image: minio/minio
    container_name: blackbird-minio
    # networks:
    #   api-network:
    #     aliases:
    #       - minio
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Web UI Port
    volumes:
      - minio_storage:/data
    env_file: .env
    command: server --console-address ":9001" /data

  pgsql:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
      - ./data/pgsql_backups:/backups
    container_name: blackbird-pgsql
    # networks:
    #   api-network:
    #     aliases:
    #       - pgsql
    ports:
      - "${POSTGRES_LOCAL_MACHINE_PORT:-5432}:5432"

# networks:
#   api-network:
#     driver: bridge
#   redis-network:
#     driver: bridge

volumes:
  minio_storage: {}

version: "3.7"
