name: Unit tests

on:
  push:
    branches:
      - main
      - features/**
      - dependabot/**
  pull_request:
    branches:
      - main

jobs:
  api-unit:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Copy env file
        run: |
          cp .env.example .env

      # - name: Echo CI
      #   run: echo ${CI}

      - name: Install
        run: yarn install --force

      - name: Start containers
        run: docker-compose -f docker-compose.yml -f test.docker-compose.yml up -d

      - name: Sleep to give things time to start
        run: sleep 60s

      - name: Print logs just to see
        run: docker logs blackbird-api

      - name: Run tests
        run: docker exec -e API_DOMAIN=http://api:3000 blackbird-api yarn test --exit

      - name: Stop containers
        if: always()
        run: docker-compose down